version: "3"
services:
  api:
    build: ./API
    ports:
      - 8000:8000
    env_file:
      - .env  # Referencia al archivo .env
    environment:
      - PINECONE_INDEX_NAME=banquetes-emails
      - CORS_ORIGINS=http://localhost:8080
    
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - api

